= Totem Blockchain Runtime(s)
:Author: Totem developers
:Revision: 0.0.1
:toc:
:sectnums:

== Intro to Totem in one-ish sentence

> Totem is a dedicated, peer-to-peer protocol for making instant and accurate accounting entries to any one or more independant accounting ledgers anywhere in the world.

You can think of it like TCP/IP for accounting data with a modern, user-friendly  app front-end.

== Description

Totem is built on the idea that accounting ledgers should be able to communicate directly with each other on a peer-to-peer network, and to achieve this we use a custom built blockchain runtime coupled with a full set of account posting recipes to create - what we believe to be  - one of the first fully decentralised products for business and consumers. 

In essence Totem is delivering a fully functional accounting ledger attached to a blockchain identity. But that is a gross under-representation of the greater project goals which are outlined elsewhere on the interwebs.

=== Why is this important?

The communication flow in accounting and book-keeping is completely broken. Your email inbox is spammed full of accounting information like, invoices, Uber receipts, flight expenses, online orders, and there is no direct connection between those accounting documents to either the payment, the reasons for the transaction or, crucially, your accounting system. 

Whichever way you try to manage this, it boils down to manual effort to  gather and send the information to your accountant, who re-encodes it _again_ and carries out much manual effort to reconcile it to business activities, payments, bank statements. 

Businesses large and small suffer equally with this same problem, *_because there is no common accounting protocol_* on which to reconnect the pieces. 

Enter Totem; stage left.

=== What we are working towards...

In our view, when an invoice is created at (for example) Uber, it should _automatically_ appear in your accounts. But we go one step further... this mechanism should not be dependent on a centrally controlled accounting software company, who will inevitably sell you licences just to have this facility. This mechanism should be completely independent of the accounting software vendor, and continue to operate, peer-to-peer, at all times, forever. 

This is the problem that Totem is solving. Once you see this ability in action, *_"much newness thing possible"_*.

=== Story so far

Totem is still an early stage product, as we started developing in earnest in December 2018 building on years of discovery and research, that evolved out of experimental projects in the blockchain and cryptocurrency space going back to 2013. 

The idea behind Totem is simple however and makes sense in a connected world. 

Even if you are not running a business, "the business of accounting records" touches everything you do, like it or not. From the receipt for a new smartphone, to your regular groceries you are bombarded with accounting data you cannot easily make use of. 

Imagine a world where you could, for example, see how much you paid for tomatoes last year? Or five years ago? Or shoes, or speeding fines... without you having to do anything special. Imagine that the information just existsed privately, for you to access any time you wanted. How could that change your life? Honestly we don't know, but it will be a bonus side effect of what Totem are building. Our main target is the ever- expanding decentralised economy - as businesses employ less and contract freelancers more, we are all moviong towards a future where our accounting is at the level of our identity. 

=== The alternatives

* Q: Can banks do this? A: No. The detail is lost in the transaction, and it's not _their_ business model to collect it. 

* Q: Can accounting software companies do this? A: Yes and no. There are too many competing players, the coverage would not be universal. Additionally it would destroy their licence-fee paying business model, and what would happen to your data if they went bust?

* Q: Can Totem do this? A: Yes. Definitely. The Totem team demoed this capability in February 2019, connecting five random parties and three tax jurisdictions, posting accounting entries in all relevant accounts on a blockchain. This means the activity of accounting will not be dependant on Totem and can be universal. 


We have been building out the full scale version ever since and Totem can already do many of the underlying communication tasks required to make this happen. We are still actively pushing new code every day.

== Application Architecture

There are several key components to the Totem Architecture which are as follows:

* the blockchain runtimes and on-chain storage, 
* the Totem BOXKEYS on-chain public key registry 
* the Totem BONSAI on-chain pre-authentication for off-chain distributed NoSQL databases
* the off-chain distributed NoSQL storage (using the Totem BONSAI protocol) 
* the off-chain global shared datasets (companies, products, places) 
* the front-end UI service, 
* the p2p encrypted communication channel, 
* the 'transactions' faucet,

Whilst much of this is established in an early form, not all of it is completed yet.

This architecture is designed in this way to allow businesses to participate in the global live network, but they can also run their own private networks should they wish to do this.

=== Privacy

The Totem Network will have privacy as a default for all created identities. The BOXKEYS is a key building-block in that process. As the development progresses we will be introducing fully encrypted storage and end-to-end communication (hence the reason for developing BOXKEYS and BONSAI) to maintain data security and privacy for everyone using any Totem network. In the longer term we will be using Full Homomorphic Encryption for obvious reasons.

== Meccano TestNet

The current version of the "Totem Live" network is the  *Meccano TestNet*. We do not plan a MainNet until we have a fully functional end-to-end product. This will likely be in later this year (2020 as of writing).

Nevertheless, you can already test and use much of the core communication and storage technology as well as the first modules which have already been built, including: 

* Identities, 
* Partners, 
* Activities, 
* Teams, 
* Timekeeping 
* Transfers, 
* BOXKEY Server,

...in our Totem Live webapp https://totem.live[here]. 

There is also a bleeding edge (read "sometimes broken") live development network https://dev.totem.live[here]. If you are a developer, you can see our entire group of developments at various build stages https://gitlab.com/totem-tech[here].

When using Totem Meccano via the links we recommend you experiment with friends, partners and other businesses (this is a peer-to-peer service after all) to get the general idea about how we are connecting and posting between parties. 

If you come across any issues, or wish to make suggestions for develoment or user experience please take the time to post them https://gitlab.com/totem-tech/issues/new[here].

=== Running a node on the Meccano network

The code in this repository will enable you to join and support Meccano as a simple node.

If you wish to become a validator or authority on the network, please contact us at mailto:info@totemaccounting.com?subject=Inquiry:%20Becoming%20a%20Validator%20or%20Authority%20on%20Totem[info@totemaccounting.com]

In most cases we expect that you can use one of our binaries to run the software or you can compile it using the instructions below.

We recommend you use on of the current binaries which can be found here.

== Trying out Totem Meccano

If you are running the binaries, skip to the  <<#binary>> section.

Otherwise if you would like to compile and run the code from source follow the instructions below.

=== Dependencies

Totem is built using the Rust languange, so you will need to install these dependencies.  

[source, shell]
----
curl https://sh.rustup.rs -sSf | sh
# on Windows download and run rustup-init.exe
# from https://rustup.rs instead

rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
rustup update stable
cargo install --git https://github.com/alexcrichton/wasm-gc
----

You will also need to install the following packages:

 - Linux:
[source, shell]
sudo apt install cmake pkg-config libssl-dev git clang libclang-dev

 - Mac:
[source, shell]
brew install cmake pkg-config openssl git llvm

 - Windows (PowerShell):
+
[source, shell]
----
# Install LLVM
# Download and install the Pre Build Windows binaries
# of LLVM  from http://releases.llvm.org/download.html

# Install OpenSSL (through vcpkg)
mkdir \Tools
cd \Tools
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg.exe install openssl:x64-windows-static

$env:OPENSSL_DIR = 'C:\Tools\vcpkg\installed\x64-windows-static'
$env:OPENSSL_STATIC = 'Yes'
[System.Environment]::SetEnvironmentVariable('OPENSSL_DIR', $env:OPENSSL_DIR, [System.EnvironmentVariableTarget]::User)
[System.Environment]::SetEnvironmentVariable('OPENSSL_STATIC', $env:OPENSSL_STATIC, [System.EnvironmentVariableTarget]::User)
----

Then, clone this repo to get the Totem source code:

[source, shell]
----
git clone https://gitlab.com/totem-tech/totem-substrate.git
cd totem-substrate
----

Then build the code:

[source, shell]
----
./scripts/build.sh  		# Builds the WebAssembly binaries
cargo build 				# Builds all native code
----

Detailed logs may be shown by running the node with the following environment variables set: `RUST_LOG=debug RUST_BACKTRACE=1 cargo run`.

Because Totem is built on Parity's Substrate framework, you can also execute all the functions that you would expect with Substrate. However this will not neceesarily run the Totem runtime modules particularly if you do not include the Totem chain specification.

=== Joining the Totem Meccano network

Starting the runtime for the Totem network maybe slightly different depending on if you compiled the code or if you are executing the binary that you downloaded.

[#compiled]
==== Executing the compiled code
Below we describe how to execute the code if you compiled the code from the repo.

Below is an example of some parameters you can use to start your node. These are not mandatory as the node will start without these if you execute either `cargo run --release` or `./target/release/totem-meccano` you can also navigate directly to the node binary that you have compiled and execute 

[source, shell]
  cd /target/release/
  ./totem-meccano

Any of these will execute the binary.

Additional Totem CLI usage options (which are identical to that of Substrate v1.0) are available and may be shown by running any of the above commands appending `--help`. 

In the following example we are running a Totem node called Alice on TCP port of 30334 with her chain database stored locally at `/tmp/alice`. 

[source, shell]
cargo run --release \-- \
  --base-path /tmp/alice \
  --alice \
  --port 30334 \

[#binary]
==== Executing the binary

Once you have downloaded the binary all you have to do is navigate to the directory and execute the code:

[source, shell]
  cd /target/release/
  ./totem-meccano

If you are running in a desktop you can also simply open the binary to begin execution. The options mentioned in <<#compiled>> only apply if you are running on the command line.

If you are successful, you will see your node syncing at https://telemetry.polkadot.io/#/Totem%20Meccano

== High Level Roadmap

The development is split into these key areas and :

* CORE MODULES/UI

The main internal development of the runtime modules supported by the front-end uers interface.

* OFF-CHAIN DATA

Storing everything on-chain is just not good practice, but building apps requires some relevant information to be stored not only in a persistant state, but it should also be _queryable_ and updatable. IPFS fails in this respect.

The normal course of action would be to create a centralised server for this data but then we get into all kinds of trouble in distributed systems. 

* NO SQL DATABASE

Totem is building a queryable database whose content-hashes are pre-authenticated in the BONSAI module meaning that the will only contain authenticated data.

In fact it does not even require any reference to the owner of the data as this is also pre-authenticated. 

We foresee a future where the Totem blockchain (acting as the authority for content and access) will co-exist with a distributed NoSQL database on a seperate P2P network.

* CRYPTOGRAPHY


* P2P (INTERNAL) COMMS
* FAUCET
* NETWORK
* SUBSTRATE STANDARD
* ARCHIVE PROCESS
* MIGRATION

=== So far

- 0.1 "PoC-1": PBFT consensus, Wasm runtime engine, basic runtime modules.
- 0.2 "PoC-2": Libp2p

=== In progress

- AfG consensus
- Improved PoS
- Smart contract runtime module

=== The future

- Splitting out runtime modules into separate repo
- Introduce substrate executable (the skeleton-key runtime)
- Introduce basic but extensible transaction queue and block-builder and place them in the executable.
- DAO runtime module
- Audit

== License

Totem is building under the same https://github.com/paritytech/substrate/blob/master/LICENSE[license] as the Substrate framework.

== Contributing Guidelines

include::CONTRIBUTING.adoc[]

=== Contributor Code of Conduct

include::CODE_OF_CONDUCT.adoc[]
